In [76]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [77]:
df = pd.read_csv("train.txt" , sep=';' ,header=None , names=['text' , 'emotion']) 

In [78]:
df.head()

text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [79]:
#for make it understanding to computer we have to classify 'emotion' into numeric values

In [80]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [81]:
unique_emotions = df['emotion'].unique() #6 unique emotions

In [82]:
emotion_num = {}
i = 0
for emo in unique_emotions: 
    emotion_num[emo] = i 
    i+=1


In [83]:
emotion_num

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [84]:
df['emotion'] = df['emotion'].map(emotion_num)

In [85]:
df['emotion']

0        0
1        0
2        1
3        2
4        1
        ..
15995    0
15996    0
15997    5
15998    1
15999    0
Name: emotion, Length: 16000, dtype: int64

In [86]:
#Other things Like coverting texts to lowercase and so others

In [87]:
df['text'] = df['text'].apply(lambda x:x.lower())

In [88]:
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...                        
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: object

In [89]:
#remove punctuations (used mostly in ML not in DL)

In [90]:
#uses string functions like 

In [91]:
import string

In [92]:
def rem_punc(text): 
    return text.translate(str.maketrans('' , '' , string.punctuation)) 

df['text'] = df['text'].apply(rem_punc)

In [93]:
df['text'][0]

'i didnt feel humiliated'

In [94]:
#now removing numbers

In [95]:
def rem_num(text): 
    new = ''
    for i in text: 
        if not i.isdigit():
            new = new+ i 
    return new 

df['text'] = df['text'].apply(rem_num)

In [96]:
#now remving links/URLs (as the data is downloaded from kaggle so it doesn't have any links)

In [97]:
#but in case you still want to do that you can use same logic as upper and for words like 'http//'

In [98]:
# now dealing with emojis or special characters we can use ascii values to identify them and then remove them 

In [99]:
#as very character has its ascii value in python which is understandable to computer

In [100]:
#ascii values are for characters that already exists but the unicode are for characters like emojis

In [101]:
def rem_emo(text): 
    new = ''
    for i in text: 
        if i.isascii():
            new = new+ i 
    return new 

df['text'] = df['text'].apply(rem_emo)

In [102]:
#the final thing is to remove stop-words because its important in ML but not for Dl its helpfull for understanding context

In [103]:
#for that we use libraries here ex. nltk

In [104]:
import nltk #NaturallanguageToolkit And There is one another Library called spaCy

In [105]:
from nltk.corpus import stopwords

In [106]:
from nltk.tokenize import word_tokenize

In [107]:
stopwords

<WordListCorpusReader in 'C:\\Users\\hp\\AppData\\Roaming\\nltk_data\\corpora\\stopwords'>

In [108]:
nltk.download('punkt') #to tokenize words
nltk.download('stopwords') #contains stop words

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [109]:
stop__words = set(stopwords.words('english'))

In [110]:
stop__words #all the stop words we need to remove

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [111]:
len(stop__words)

198

#example 

In [112]:
df.loc[1]['text'] 

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [113]:
#first we need to convert str into array and by comparing values in the stop__words we can remove them in array itself and them convert it back to str

In [114]:
#this procedure for reading of words uniquely in form of str to array is called tokenization #similar to split but tokenization is better for ML scenarios

In [115]:
#for tokenization and removing stop__words we will use function

In [116]:
def remove(text): 
    words = word_tokenize(text) #works onlt if punkt is downloaded and if you cant find punkt use "text.split()"
    cleaned = []    
    for i in words: 
        if i not in stop__words: 
            cleaned.append(i)
    return ' '.join(cleaned)

df['text'] = df['text'].apply(remove)

In [117]:
#errored so do, 
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import pandas as pd

# download required nltk data
nltk.download('punkt')
nltk.download('stopwords')

# define stop words
stop_words = set(stopwords.words('english'))

# define function
def remove(text):
    words = word_tokenize(text)
    cleaned = [word for word in words if word.lower() not in stop_words]
    return ' '.join(cleaned)

# example dataframe
df2 = pd.DataFrame({'text': ['This is an example sentence for cleaning text data.']})

# apply the function
df['text'] = df['text'].apply(remove)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [118]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [119]:
df['text'][1]

'go feeling hopeless damned hopeful around someone cares awake'

In [120]:
#So this was all about NLP text Preprocessing

In [1]:
#BagOfWords Implementation

In [9]:
from sklearn.feature_extraction.text import CountVectorizer


#example data

document = ['i love pizza' , 'pizza is the best' ,'i love pasta' ,'pasta is great']

vector = CountVectorizer()  #All the preprocessing also is inbuilt in this as parameters so you can done using parameters here but doing it explicitily is a good practice

x= vector.fit_transform(document) 
print(vector.get_feature_names_out())  #Order doesn.t matter bydefault it give Vocabulary list in Alphabetical order
print(x.toarray())
print(x)

['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']
[[0 0 0 1 0 1 0]
 [1 0 1 0 0 1 1]
 [0 0 0 1 1 0 0]
 [0 1 1 0 1 0 0]]
  (0, 3)	1
  (0, 5)	1
  (1, 5)	1
  (1, 2)	1
  (1, 6)	1
  (1, 0)	1
  (2, 3)	1
  (2, 4)	1
  (3, 2)	1
  (3, 4)	1
  (3, 1)	1


In [10]:
#With n-gram range illustration

In [11]:
#example data
document = ['i love pizza' , 'pizza is the best' ,'i love pasta' ,'pasta is great']

vector = CountVectorizer(ngram_range=(1,2)) 

x= vector.fit_transform(document) 
print(vector.get_feature_names_out())  #Order doesn.t matter bydefault it give Vocabulary list in Alphabetical order
print(x.toarray())
print(x)

['best' 'great' 'is' 'is great' 'is the' 'love' 'love pasta' 'love pizza'
 'pasta' 'pasta is' 'pizza' 'pizza is' 'the' 'the best']
[[0 0 0 0 0 1 0 1 0 0 1 0 0 0]
 [1 0 1 0 1 0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 1 1 0 1 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 1 1 0 0 0 0]]
  (0, 5)	1
  (0, 10)	1
  (0, 7)	1
  (1, 10)	1
  (1, 2)	1
  (1, 12)	1
  (1, 0)	1
  (1, 11)	1
  (1, 4)	1
  (1, 13)	1
  (2, 5)	1
  (2, 8)	1
  (2, 6)	1
  (3, 2)	1
  (3, 8)	1
  (3, 1)	1
  (3, 9)	1
  (3, 3)	1


In [12]:
#example data
document = ['i love pizza' , 'pizza is the best' ,'i love pasta' ,'pasta is great']

vector = CountVectorizer(ngram_range=(2,2)) 

x= vector.fit_transform(document) 
print(vector.get_feature_names_out())  #Order doesn.t matter bydefault it give Vocabulary list in Alphabetical order
print(x.toarray())
print(x)

['is great' 'is the' 'love pasta' 'love pizza' 'pasta is' 'pizza is'
 'the best']
[[0 0 0 1 0 0 0]
 [0 1 0 0 0 1 1]
 [0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0]]
  (0, 3)	1
  (1, 5)	1
  (1, 1)	1
  (1, 6)	1
  (2, 2)	1
  (3, 4)	1
  (3, 0)	1


In [13]:
#example data
document = ['i love pizza' , 'pizza is the best' ,'i love pasta' ,'pasta is great']

vector = CountVectorizer(ngram_range=(4,4)) 

x= vector.fit_transform(document) 
print(vector.get_feature_names_out())  #Order doesn.t matter bydefault it give Vocabulary list in Alphabetical order
print(x.toarray())
print(x)

['pizza is the best']
[[0]
 [1]
 [0]
 [0]]
  (1, 0)	1
